# Production profile — PostgreSQL on Render
server.port=8080
spring.datasource.url=jdbc:postgresql://dpg-d6tjsuuuk2gs738sm6jg-a/chitchat_st1n
spring.datasource.username=chitchat_st1n_user
spring.datasource.password=AMSZqhS3MgCQO1S3A467V60axr9YFhFz
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.web.resources.static-locations=classpath:/static/
