-- ============================================================
-- ChitChat Database Schema
-- Auto-generated by Hibernate (ddl-auto=update) on first run.
-- This file documents the full schema for reference.
-- ============================================================

-- Create database (if running manually)
CREATE DATABASE IF NOT EXISTS chitchat;
USE chitchat;

-- ── Users ──────────────────────────────────────────────────
-- Stores registered user accounts.
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    fname           VARCHAR(255) NOT NULL,
    lname           VARCHAR(255) NOT NULL,
    username        VARCHAR(255) NOT NULL UNIQUE,
    hashed_password VARCHAR(255) NOT NULL,
    last_online     VARCHAR(255),
    logged_in       BOOLEAN DEFAULT FALSE,
    avatar_url      TEXT,
    preferences     TEXT        -- JSON blob (UserPreferences)
);

-- ── Friend graph ───────────────────────────────────────────
-- Bidirectional friendship (each direction stored separately).
CREATE TABLE IF NOT EXISTS user_friends (
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id)   REFERENCES users(id),
    FOREIGN KEY (friend_id) REFERENCES users(id)
);

-- ── Blocked users ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_blocked (
    user_id    BIGINT NOT NULL,
    blocked_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, blocked_id),
    FOREIGN KEY (user_id)    REFERENCES users(id),
    FOREIGN KEY (blocked_id) REFERENCES users(id)
);

-- ── Pending friend requests ────────────────────────────────
CREATE TABLE IF NOT EXISTS user_pending_requests (
    user_id      BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, requester_id),
    FOREIGN KEY (user_id)      REFERENCES users(id),
    FOREIGN KEY (requester_id) REFERENCES users(id)
);

-- ── Chat messages ──────────────────────────────────────────
-- Stores all messages: public, private, and group room.
-- receiver is NULL for public/room messages.
-- room_id is NULL for public/private messages.
CREATE TABLE IF NOT EXISTS chat_messages (
    id        VARCHAR(36) PRIMARY KEY,  -- UUID
    type      VARCHAR(50),              -- MessageType enum value
    sender    VARCHAR(255),
    receiver  VARCHAR(255),             -- NULL for public/room
    room_id   VARCHAR(255),             -- NULL for public/private
    content   TEXT,
    timestamp DATETIME,
    edited    BOOLEAN DEFAULT FALSE,
    deleted   BOOLEAN DEFAULT FALSE
);

-- ── Message reactions ──────────────────────────────────────
-- Emoji reactions attached to a message by a user.
CREATE TABLE IF NOT EXISTS message_reactions (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    message_id VARCHAR(36) NOT NULL,
    username   VARCHAR(255),
    emoji      VARCHAR(10),
    FOREIGN KEY (message_id) REFERENCES chat_messages(id)
);

-- ── Chat rooms ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS chat_rooms (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_by  VARCHAR(255) NOT NULL
);

-- ── Room members ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS room_members (
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (room_id, user_id),
    FOREIGN KEY (room_id) REFERENCES chat_rooms(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);
